# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\development\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1366, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1366, 768))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 471, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAcceptDrops(False)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(840, 520, 521, 221))
        self.groupBox.setObjectName("groupBox")
        self.listCommand = QtWidgets.QListWidget(self.groupBox)
        self.listCommand.setGeometry(QtCore.QRect(5, 15, 511, 201))
        self.listCommand.setObjectName("listCommand")

        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(840, 0, 522, 522))
        self.groupBox_3.setObjectName("groupBox_3")

        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(5, 15, 512, 512))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\development\\../res/default.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.group_text = QtWidgets.QGroupBox(self.centralwidget)
        self.group_text.setGeometry(QtCore.QRect(10, 99, 821, 641))
        self.group_text.setObjectName("group_text")

        self.textEdit = QtWidgets.QTextEdit(self.group_text)
        self.textEdit.setGeometry(QtCore.QRect(5, 15, 811, 621))
        self.textEdit.setObjectName("textEdit")
        self.cmdStart = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.cmdStart.setGeometry(QtCore.QRect(480, 10, 185, 41))
        self.cmdStart.setObjectName("cmdStart")
        self.cmdStop = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.cmdStop.setEnabled(False)
        self.cmdStop.setGeometry(QtCore.QRect(480, 50, 185, 41))
        self.cmdStop.setObjectName("cmdStop")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VCOS - Voice Controlled OpenSCAD"))
        self.label_2.setText(_translate("MainWindow", "VCOS-W 0.0.1 "))
        self.label_4.setText(_translate("MainWindow", "State: Listening "))
        self.groupBox.setTitle(_translate("MainWindow", "Commands"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Render View"))
        self.group_text.setTitle(_translate("MainWindow", "Text View"))
        self.cmdStart.setText(_translate("MainWindow", "Start"))
        self.cmdStop.setText(_translate("MainWindow", "Stop"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
